// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zarzadzanie_uczelnia;

#nullable disable

namespace Zarzadzanie_uczelnia.Migrations
{
    [DbContext(typeof(UczelniaContext))]
    [Migration("20260425103025_InitClean")]
    partial class InitClean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zarzadzanie_uczelnia.Grupa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("KierunekID")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("KierunekID");

                    b.ToTable("Grupy");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Kierunek", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Kierunki");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrupaID")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NrTelefonu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rocznik")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("GrupaID");

                    b.ToTable("Studenci");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Oceny", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateOnly>("DataWystawienia")
                        .HasColumnType("date");

                    b.Property<int>("GrupaID")
                        .HasColumnType("int");

                    b.Property<int>("PrzedmiotID")
                        .HasColumnType("int");

                    b.Property<int?>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("WartoscOceny")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("GrupaID");

                    b.HasIndex("PrzedmiotID");

                    b.HasIndex("StudentID");

                    b.ToTable("Ocena");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Przedmioty", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ECTS")
                        .HasColumnType("int");

                    b.Property<int>("KierunekID")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("KierunekID");

                    b.ToTable("Przedmiot");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Grupa", b =>
                {
                    b.HasOne("Zarzadzanie_uczelnia.Kierunek", "Kierunek")
                        .WithMany("Grupy")
                        .HasForeignKey("KierunekID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kierunek");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Models.Student", b =>
                {
                    b.HasOne("Zarzadzanie_uczelnia.Grupa", "Grupa")
                        .WithMany("Studenci")
                        .HasForeignKey("GrupaID");

                    b.Navigation("Grupa");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Oceny", b =>
                {
                    b.HasOne("Zarzadzanie_uczelnia.Grupa", "Grupa")
                        .WithMany("Oceny")
                        .HasForeignKey("GrupaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zarzadzanie_uczelnia.Przedmioty", "Przedmiot")
                        .WithMany("Oceny")
                        .HasForeignKey("PrzedmiotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zarzadzanie_uczelnia.Models.Student", null)
                        .WithMany("Oceny")
                        .HasForeignKey("StudentID");

                    b.Navigation("Grupa");

                    b.Navigation("Przedmiot");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Przedmioty", b =>
                {
                    b.HasOne("Zarzadzanie_uczelnia.Kierunek", "Kierunek")
                        .WithMany("Przedmioty")
                        .HasForeignKey("KierunekID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kierunek");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Grupa", b =>
                {
                    b.Navigation("Oceny");

                    b.Navigation("Studenci");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Kierunek", b =>
                {
                    b.Navigation("Grupy");

                    b.Navigation("Przedmioty");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Models.Student", b =>
                {
                    b.Navigation("Oceny");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Przedmioty", b =>
                {
                    b.Navigation("Oceny");
                });
#pragma warning restore 612, 618
        }
    }
}
