// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zarzadzanie_uczelnia;

#nullable disable

namespace Zarzadzanie_uczelnia.Migrations
{
    [DbContext(typeof(UczelniaContext))]
    [Migration("20260327091027_2")]
    partial class _2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zarzadzanie_uczelnia.Grupa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("KierunekID")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("KierunekID");

                    b.ToTable("Grupy");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Kierunek", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Kierunki");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Oceny", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateOnly>("DataWystawienia")
                        .HasColumnType("date");

                    b.Property<int?>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("WartoscOceny")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StudentID");

                    b.ToTable("Ocena");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Przedmioty", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ECTS")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OcenyID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OcenyID");

                    b.ToTable("Przedmiot");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrupaID")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NrTelefonu")
                        .HasColumnType("int");

                    b.Property<int>("Rocznik")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("GrupaID");

                    b.ToTable("Studenci");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Grupa", b =>
                {
                    b.HasOne("Zarzadzanie_uczelnia.Kierunek", null)
                        .WithMany("Grupy")
                        .HasForeignKey("KierunekID");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Oceny", b =>
                {
                    b.HasOne("Zarzadzanie_uczelnia.Student", null)
                        .WithMany("Ocena")
                        .HasForeignKey("StudentID");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Przedmioty", b =>
                {
                    b.HasOne("Zarzadzanie_uczelnia.Oceny", null)
                        .WithMany("Przedmiot")
                        .HasForeignKey("OcenyID");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Student", b =>
                {
                    b.HasOne("Zarzadzanie_uczelnia.Grupa", null)
                        .WithMany("Studenci")
                        .HasForeignKey("GrupaID");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Grupa", b =>
                {
                    b.Navigation("Studenci");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Kierunek", b =>
                {
                    b.Navigation("Grupy");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Oceny", b =>
                {
                    b.Navigation("Przedmiot");
                });

            modelBuilder.Entity("Zarzadzanie_uczelnia.Student", b =>
                {
                    b.Navigation("Ocena");
                });
#pragma warning restore 612, 618
        }
    }
}
